### ISSUE TITLE
Any plan on supporting multiple custom tags?

### ISSUE THREAD

**Issue by iceycake** [intelsdi-x/snap-plugin-publisher-opentsdb#14]
The current plugin only supports a single tag (hostname).  It's less useful especially in AWS EC2 environment since hostname is subjective to change all the time.

**Comment by IRCody** [comment]
I think adding custom tags seems reasonable. What do you think is the most intuitive way to add them? My first thought is to add an optional config item that looks something like:

`"Tags": "tag1=thing,tag2=thing2"`

**Comment by iceycake** [comment]
We are using YAML for the task definition, may be list of maps?

```
   tags:
      tag1:
          value: value2
      tag2:
          value: value2
```

**Comment by IRCody** [comment]
Because of the way the plugin parses the config (by using a library from snap) making that change might be a bigger ask. For yaml would something like:
```yaml
---
tags:
  thing1=value1,thing2=value2
```
Be an improvement?

**Comment by iceycake** [comment]
I see.  If that's case, your suggestion would work.

**Comment by IRCody** [comment]
@iceycake: There is actually a way already to add tags to the task manifest that was recently added to snap. It looks like:
```yaml
---
  collect: 
    metrics: 
      /foo/bar:
        version: 1
      /foo/baz:      
    tags:
      /foo/bar:
        tag1: "val1"
        tag2: "val2"
      /foo/baz:
        tag3: "val3"
```

This will apply to all plugins in the workflow. For a full example look at [sample](https://github.com/intelsdi-x/snap/blob/master/scheduler/wmap/sample/1.yml). Does this fit what you needed?
